AppModels/urls.py
from django.urls import path, include
from .views import  EventPaginationTemplateView, Home, AllPersonORMViewList, PersonInCityORMViewList, \
                    TopCityTemplateView, AllPersonRawiewList, PersonInCityRAWiewList, TopCityRawTemplateView, EventPaginationRawTemplateView



app_name = 'test'
urlpatterns_orm = [
    path('person-all', AllPersonORMViewList.as_view(), name='orm-person-all'),
    path('city-persons/<int:city_id>', PersonInCityORMViewList.as_view(), name='orm-city-persons'),
    path('top-city', TopCityTemplateView.as_view(), name='orm-top-city'),
    path('paginator-event', EventPaginationTemplateView.as_view(), name='orm-paginator-event'),
]

urlpatterns_raw = [
    path('person-all', AllPersonRawiewList.as_view(), name='raw-person-all'),
    path('city-persons/<int:city_id>', PersonInCityRAWiewList.as_view(), name='raw-city-persons'),
    path('top-city', TopCityRawTemplateView.as_view(), name='raw-top-city'),
    path('paginator-event', EventPaginationRawTemplateView.as_view(), name='raw-paginator-event'),
]



urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('orm/', include(urlpatterns_orm)),    
    path('raw/', include(urlpatterns_raw)),    
]

pyTests/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppModels.urls')),

]

AppModels/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'    
    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"
    
class Person(models.Model):
    name = models.CharField(max_length=100)    
    city = models.ForeignKey(City, verbose_name="Город", on_delete=models.PROTECT)
    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"


class Event(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    class Meta:
        verbose_name = "Событие"
        verbose_name_plural = "Спбытия"

AppModels/views.py
from django.core import paginator
from django.db.models.expressions import F
from AppModels.models import City, Event, Person
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.core.paginator import Paginator
from django.db.models import  Count

# Create your views here.


class  Home(TemplateView):
    template_name = 'home.html'  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        return  context    

# ORM 
class AllPersonORMViewList(ListView):
    """
        Вывести список людей и городов где они живут?
    """
    template_name = 'orm_all_person.html'
    paginate_by = 24
    model = Person


    
class PersonInCityORMViewList(ListView):
    """ 
        Вывести всех людей, живущих в городе N
    """    
    model = Person
    paginate_by = 24
    template_name = 'orm_person_in_city.html'

    def get_queryset(self) :
        city_id = self.kwargs.get('city_id')       

        query = Person.objects.filter(city=city_id)

        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)                
        city_id = self.kwargs.get('city_id')
        city    = City.objects.get(pk=city_id)                
        context['city'] = city
        return context

class TopCityTemplateView(TemplateView):
    """
        Вывести 5 городов с наибольшим населением, упорядочив по убыванию.
    """
    template_name = 'orm_top_city.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)                

        person_count = Person.objects.values_list('city_id').annotate(cnt=Count('id') ).order_by('-cnt', 'city_id')[:5]        

        person_dict = { p[0]: p[1] for p in person_count }
        object_list = City.objects.filter(id__in=[city[0] for city in person_count])        
        context['object_list'] = object_list
        context['person_dict'] = person_dict

        return context


class EventPaginationTemplateView(TemplateView):
    """ 
        Реализовать пагинацию с сортировкой по разнице дат
    """
    template_name   = 'orm_event_pagination.html'
    model           = Event
    paginate_by     = 24
    
    def get_context_data(self, **kwargs):
        page = self.request.GET.get('page', 1)        
        context = super().get_context_data(**kwargs)                

        days = Event.objects.all().values_list('id').annotate(days=F('end_date')-F('start_date')).order_by('-days')       

        days_dict = { day[0]: day[1].days for day in days }
        paginator   = Paginator(days, self.paginate_by)
        page_obj    = paginator.get_page(page)        
        events = Event.objects.filter(id__in=[id[0] for id in page_obj.object_list])
        context['object_list']  = events
        context['page_obj']     = page_obj        
        context['days_dict']    = days_dict        
        return context


class AllPersonRawiewList(ListView):
    """
        Вывести список людей и городов где они живут?
    """
    template_name = 'raw_all_person.html'
    paginate_by = 24    
    model = Person

    def get_queryset(self) :
        query = Person.objects.raw(""" 
                select a.id, a.city_id, a.name, b.name as city_name  from public."AppModels_person" a
                join   public."AppModels_city" b on a.city_id = b.id 
                """)
        return query
    
class PersonInCityRAWiewList(ListView):
    """ 
        Вывести всех людей, живущих в городе N
    """    
    model = Person
    paginate_by = 24
    template_name = 'raw_person_in_city.html'

    def get_queryset(self) :
        city_id = self.kwargs.get('city_id')               
        query = Person.objects.raw(""" 
                select a.id, a.city_id, a.name from public."AppModels_person" a                
                where a.city_id = %s
                """, [city_id])
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)                
        city_id = self.kwargs.get('city_id')
        city    = City.objects.raw( """ 
                    select a.id,  a.name, count(b.id) as count_person  from public."AppModels_city" a
                    join public."AppModels_person" b on b.city_id = a.id 
                    where a.id = %s
                    group by a.id, a.name
                """, [city_id])
        context['city'] = city[0]
        return context

class TopCityRawTemplateView(TemplateView):
    """
        Вывести 5 городов с наибольшим населением, упорядочив по убыванию.
    """
    template_name = 'raw_top_city.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)                

        city    = City.objects.raw( """ 
                    select * from (  select a.id,  a.name, count(b.id) as count_person  from public."AppModels_city" a
                    join public."AppModels_person" b on b.city_id = a.id
                    group by a.id, a.name ) a
                    order by count_person desc, id  asc
                    limit 5
                """)        
        context['object_list'] = city
        return context        

class EventPaginationRawTemplateView(ListView):
    """ 
        Реализовать пагинацию с сортировкой по разнице дат
    """
    template_name   = 'raw_event_pagination.html'
    model           = Event
    paginate_by     = 24

    def get_queryset(self) :
        query = Event.objects.raw(""" 
                select * from (
                        select a.id , a.start_date, a.end_date, DATE_PART('day',  a.end_date-a.start_date) as days  
                        from public."AppModels_event" a 
                    ) a
                    order by days desc, id asc
                """)        
        return query
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)                        
        return context        
    

templates/core/core.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        {% load static %}                    
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block meta %}       
                <title>Тестирование</title>
                <meta name="description" content="">
                <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}    
        {% block styles %}        
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/' %}{{css_file_name}}">
        {% endblock styles %}                
        <script type="text/javascript" src="{% static '/js/rxjs.min.js' %}" ></script>                                   
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>        
        
    </head>
    <body>     
        {% block body %}                
            
        {% endblock body %}            
    </body>
</html>

templates/html/home.html
{% extends 'core.html' %}
{% block body %}        
    <div class="container">
        <div class="row">
            <div class="col-2">
            <h3>ORM</h3>
            <div class="list-group">                            
                <a class="list-group-item" href="{% url 'test:orm-person-all' %}"> список людей и городов где они живут </a>                                  
                <a class="list-group-item" href="{% url 'test:orm-top-city' %}"> Вывести 5 городов с наибольшим населением, упорядочив по убыванию </a>                                  
                <a class="list-group-item" href="{% url 'test:orm-paginator-event' %}"> Реализовать пагинацию с сортировкой по разнице дат</a>                                  
            </div>                
            <h3>RAW</h3>
            <div class="list-group">                            
                <a class="list-group-item" href="{% url 'test:raw-person-all' %}"> список людей и городов где они живут </a>                                              
                <a class="list-group-item" href="{% url 'test:raw-top-city' %}"> Вывести 5 городов с наибольшим населением, упорядочив по убыванию </a>                         
                <a class="list-group-item" href="{% url 'test:raw-paginator-event' %}"> Реализовать пагинацию с сортировкой по разнице дат</a>                                                           
            </div>                    

            </div>
            <div class="col-10">
                {% block home_form %}

                {% endblock home_form %}
            </div>

        </div>          

    </div>              
{% endblock body %}            

templates/html/orm_all_person.html
{% extends 'home.html' %}
{% block home_form %}            
    <div class="container">
          <div class="row">
            {% for o  in  object_list %}            
            <div class="col-2">
                {{o.id}}    
            </div>
            <div class="col-5">
                {{o.name}}    
            </div>
            <div class="col-5">
                <a href="{% url 'test:orm-city-persons' o.city_id %}">{{o.city.name}}</a>                                
            </div>
            {% endfor %}    
          </div>          
    </div>  

    {% comment %} копи-паста из доков   {% endcomment %}
     <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> 
            
{% endblock home_form %}            

templates/html/orm_event_pagination.html
{% extends 'home.html' %}
{% load tags %}
{% block home_form %}          

    <div class="container">                      
            {% for o in  object_list %}            
            <div class="row">
                <div class="col-1">
                    {{o.id}}    
                </div>
                <div class="col-5">
                    {{ o.start_date }}
                </div>                
                <div class="col-5">
                    {{ o.end_date }}
                </div>              
                <div class="col-1">
                    {% get_result id=o.id  dict_list=days_dict %}
                </div>                  
            </div>                          
            {% endfor %}      
                   
    </div>  

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> 
{% endblock home_form %}            

templates/html/orm_person_in_city.html
{% extends 'home.html' %}
{% block home_form %}          
    <div class="container">
            <div class="row">
                  <div class="col-12">
                    <h3>
                        {{city.name}}     
                    </h3>
                </div>
            </div>
          <div class="row">
            {% for o in  object_list %}            
                <div class="col-2">
                    {{o.id}}    
                </div>
                <div class="col-10">
                    {{o.name}}    
                </div>
            {% endfor %}    
          </div>          
    </div>  

    {% comment %} копи-паста из доков   {% endcomment %}
     <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> 
            
{% endblock home_form %}            

templates/html/orm_top_city.html
{% extends 'home.html' %}
{% load tags %}
{% block home_form %}          
    <div class="container">                      
            {% for o in  object_list %}            
            <div class="row">
                <div class="col-1">
                    {{o.id}}    
                </div>
                <div class="col-10">
                    <a href="{% url 'test:orm-city-persons' o.id %}">{{o.name}}</a>                                                    
                </div>
                <div class="col-1">
                    {% get_result id=o.id  dict_list=person_dict %}
                </div>                  
            </div>                          
            {% endfor %}              
    </div>  
{% endblock home_form %}            

templates/html/raw_all_person.html
{% extends 'home.html' %}
{% block home_form %}            
    <div class="container">
          <div class="row">
            {% for o  in  object_list %}            
            <div class="col-2">
                {{o.id}}    
            </div>
            <div class="col-5">
                {{o.name}}    
            </div>
            <div class="col-5">
                <a href="{% url 'test:raw-city-persons' o.city_id %}">{{o.city_name}}</a>                                
            </div>
            {% endfor %}    
          </div>          
    </div>  

    {% comment %} копи-паста из доков   {% endcomment %}
     <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> 
            
{% endblock home_form %}            

templates/html/raw_event_pagination.html
{% extends 'home.html' %}
{% load tags %}
{% block home_form %}          

    <div class="container">                      
            {% for o in  object_list %}            
            <div class="row">
                <div class="col-1">
                    {{o.id}}    
                </div>
                <div class="col-5">
                    {{ o.start_date }}
                </div>                
                <div class="col-5">
                    {{ o.end_date }}
                </div>              
                <div class="col-1">
                    {{ o.days }}
                </div>                  
            </div>                          
            {% endfor %}      
                   
    </div>  

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> 
{% endblock home_form %}            

templates/html/raw_person_in_city.html
{% extends 'home.html' %}
{% block home_form %}          
    <div class="container">
            <div class="row">
                  <div class="col-12">
                    <h3>
                        {{city.name}}
                    </h3>
                    <h3>
                        итого: {{city.count_person}}
                    </h3>
                </div>
            </div>
          <div class="row">
            {% for o in  object_list %}            
                <div class="col-2">
                    {{o.id}}    
                </div>
                <div class="col-10">
                    {{o.name}}    
                </div>
            {% endfor %}    
          </div>          
    </div>  

    {% comment %} копи-паста из доков   {% endcomment %}
     <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> 
            
{% endblock home_form %}            

templates/html/raw_top_city.html
{% extends 'home.html' %}
{% load tags %}
{% block home_form %}          
    <div class="container">                      
            {% for o in  object_list %}            
            <div class="row">
                <div class="col-1">
                    {{o.id}}    
                </div>
                <div class="col-10">
                    <a href="{% url 'test:orm-city-persons' o.id %}">{{o.name}}</a>                                                    
                </div>
                <div class="col-1">
                    {{o.count_person}}    
                </div>                  
            </div>                          
            {% endfor %}              
    </div>  
{% endblock home_form %}            

templates/widgets/bt5_input_btn.html
<div class="input-group mb-3">
  <input type="text" class="form-control" aria-label="Text input with segmented dropdown button">
  <button type="button" class="btn btn-outline-secondary">Action</button>
</div>